FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /AlamoCorp.WebAPI

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /AlamoCorp.WebAPI
COPY --from=build-env /AlamoCorp.WebAPI/out .
ENTRYPOINT ["dotnet", "AlamoCorp.WebAPI.dll"]
